version: '2'
services:
    cambistadigital-app:
        image: cambistadigital
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cambistadigital-mysql:3306/cambistadigital?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://cambistadigital-elasticsearch:9200
        ports:
            - 8080:8080
    cambistadigital-mysql:
        extends:
            file: mysql.yml
            service: cambistadigital-mysql
    cambistadigital-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: cambistadigital-elasticsearch
